### PR TITLE
check for more parry abilities

### LINKED ISSUE #348: Avoidance, Miss of the Mob not Included
## Bug description
Miss chance of the mob is not added when calculating the avoidance chance
As seen on screenshot (Shaman 60):
Block: 49.44 %
Dodge: 19.98 %
Parry: 14.44  %
Avoidance: 49.44+14.44+19.98 = 83.86 %
it had to be like ~ 98% when miss of the mob is also added. but it is missing

## Screenshots
Image

## Version
EVS v4.1.0
Season Of Discovery

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Fixes #348

### CODE REVIEW

File: Modules/Data/Defense.lua [hunk 1]
```diff
@@ -106,20 +128,29 @@ function Data:GetDefenseValue()
     return skillRank + skillModifier
 end
 
+---@return string
+function Data:GetEnemyMissChance()
+    return DataUtils:Round(_Defense:GetEnemyMissChance(), 2) .. "%"
+end
```
Comment (BreakBB) [inline Modules/Data/Defense.lua:134]:
```suggestion

Since this is not used anywhere, I would not add it.

```suggestion
```

Comment (Alessandro-Barbieri) [reply Modules/Data/Defense.lua]: removed

**Comment by BreakBB** [comment]
Btw @Alessandro-Barbieri it would be great if you would not force push changes to the PRs. That way it's harder to review the latest changes you did. Since nothing else changed, you can do a regular push on the same branch and the PR gets updated automatically 👌🏻
