### PR TITLE
Fixes

### LINKED ISSUE #366: mp5 from items set
- [x] [bloodsoul embrace](https://www.wowhead.com/classic/item-set=443/bloodsoul-embrace)

tbc
- [x] [fel iron chain](https://www.wowhead.com/tbc/item-set=561/fel-iron-chain)
- [x] [windhawk armor](https://www.wowhead.com/tbc/item-set=618/windhawk-armor)

reworked in tbc
- [x] [green dragon mail](https://www.wowhead.com/tbc/item-set=490/green-dragon-mail)
- [x] [stormrage raiment](https://www.wowhead.com/tbc/item-set=214/stormrage-raiment)
- [x] [vestments of transcendence](https://www.wowhead.com/tbc/item-set=211/vestments-of-transcendence)

reworked in wotlk
- [x] [Augur's Regalia](https://www.wowhead.com/wotlk/item-set=476/augurs-regalia)
- [x] [Bloodsoul Embrace](https://www.wowhead.com/wotlk/item-set=443/bloodsoul-embrace)
- [x] [Green Dragon Mail](https://www.wowhead.com/wotlk/item-set=490/green-dragon-mail)
- [x] [Freethinker's Armor](https://www.wowhead.com/wotlk/item-set=475/freethinkers-armor)
- [x] [Windhawk Armor](https://www.wowhead.com/wotlk/item-set=618/windhawk-armor)
- [x] [Fel Iron Chain](https://www.wowhead.com/wotlk/item-set=561/fel-iron-chain)
- [x] [Haruspex's Garb](https://www.wowhead.com/wotlk/item-set=479/haruspexs-garb)
- [x] [stormrage raiment](https://www.wowhead.com/wotlk/item-set=214/stormrage-raiment)
- [x] [vestments of transcendence](https://www.wowhead.com/wotlk/item-set=211/vestments-of-transcendence)

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
#366

### CODE REVIEW

File: Modules/Data/Constants.lua [hunk 1]
```diff
@@ -21,14 +21,19 @@ Data.WARLOCK = 9
...
 
 Data.setNames = {
+    AUGURS_REGALIA = "Augur's Regalia",
     BATTLEGEAR_OF_MIGHT = "Battlegear of Might",
+    BLOODSOUL_EMBRACE="Bloodsoul Embrace",
+    FEL_IRON_CHAIN="Fel Iron Chain",
+    FREETHINKERS_ARMOR = "Freethinker's Armor",
+    GREEN_DRAGON_MAIL="Green Dragon Mail",
+    HARUSPEXS_GARB = "Haruspex's Garb",
+    LIVING_GREEN_DRAGON_MAIL="Living Green Dragon Mail",
```
Comment (BreakBB) [inline Modules/Data/Constants.lua:31]:
```suggestion
    BLOODSOUL_EMBRACE = "Bloodsoul Embrace",
    FEL_IRON_CHAIN = "Fel Iron Chain",
    FREETHINKERS_ARMOR = "Freethinker's Armor",
    GREEN_DRAGON_MAIL = "Green Dragon Mail",
    HARUSPEXS_GARB = "Haruspex's Garb",
    LIVING_GREEN_DRAGON_MAIL = "Living Green Dragon Mail",
```

File: Modules/Data/Constants.lua [hunk 2]
```diff
@@ -21,14 +21,19 @@ Data.WARLOCK = 9
...
     STORMRAGE_RAIMENT = "Stormrage Raiment",
-    VESTMENTS_OF_TRANSCENDENCE = "Vestments of Transcendence",
     TEN_STORMS = "The Ten Storms",
     THE_EARTHSHATTERER = "The Earthshatterer",
-    HARUSPEXS_GARB = "Haruspex's Garb",
-    AUGURS_REGALIA = "Augur's Regalia",
-    FREETHINKERS_ARMOR = "Freethinker's Armor"
+    VESTMENTS_OF_TRANSCENDENCE = "Vestments of Transcendence",
+    WINDHAWK_ARMOR="Windhawk Armor",
```
Comment (BreakBB) [inline Modules/Data/Constants.lua:36]:
```suggestion
    WINDHAWK_ARMOR = "Windhawk Armor",
```

File: Modules/Data/ItemSets.lua [hunk 3]
```diff
@@ -56,45 +88,88 @@ local itemSets = {
...
-    elseif classId == Data.DRUID then
-        return Data:IsSetBonusActive(setNames.STORMRAGE_RAIMENT, 3)
-    end
+    return (ECS.IsClassic and (
+                    Data:IsSetBonusActive(setNames.GREEN_DRAGON_MAIL, 3) or
+                    (classId == Data.DRUID and Data:IsSetBonusActive(setNames.STORMRAGE_RAIMENT, 3)) or
+                    (classId == Data.PRIEST and Data:IsSetBonusActive(setNames.VESTMENTS_OF_TRANSCENDENCE, 3)) or
+                    (ECS.IsSod and Data:IsSetBonusActive(setNames.LIVING_GREEN_DRAGON_MAIL, 3))
+                )
+            )
```
Comment (BreakBB) [inline Modules/Data/ItemSets.lua:115]:
```suggestion
        Data:IsSetBonusActive(setNames.GREEN_DRAGON_MAIL, 3) or
        (classId == Data.DRUID and Data:IsSetBonusActive(setNames.STORMRAGE_RAIMENT, 3)) or
        (classId == Data.PRIEST and Data:IsSetBonusActive(setNames.VESTMENTS_OF_TRANSCENDENCE, 3)) or
        (ECS.IsSod and Data:IsSetBonusActive(setNames.LIVING_GREEN_DRAGON_MAIL, 3))
    ))
```

File: Modules/Data/DataUtils.lua [hunk 4]
```diff
@@ -103,7 +103,7 @@ function DataUtils.GetRuneForEquipSlot(equipSlot)
     local runeInfo = C_Engraving.GetRuneForEquipmentSlot(slotId)
 
     if runeInfo then
-        return runeInfo.skillLineAbilityID
+        return runeInfo.itemEnchantmentID
```
Comment (BreakBB) [inline Modules/Data/DataUtils.lua:106]:
```suggestion
        return runeInfo.skillLineAbilityID
```

File: Modules/Data/SpellCrit.lua [hunk 5]
```diff
@@ -34,7 +34,7 @@ function _SpellCrit:GetSpellCritFromBuffs(school)
             break
         end
 
-        if spellId == 30708 then
+        if ECS.IsTbc and spellId == 30708 then
```
Comment (BreakBB) [inline Modules/Data/SpellCrit.lua:37]:
```suggestion
        if spellId == 30708 then
```

File: Modules/Data/SpellCrit.lua [hunk 6]
```diff
@@ -60,15 +60,9 @@ function _SpellCrit:GetSpellCritFromBuffs(school)
         if (ECS.IsWotlk and spellId == 51470) then
             mod = mod + 5 -- 5% from Elemental Oath Rank 2
         end
-        if (ECS.IsWotlk and school == Data.FIRE_SCHOOL and spellId == 11129) then
-            mod = mod + 50 -- 50% from Combustion
-        end
-        if (ECS.IsWotlk and school == Data.FIRE_SCHOOL and spellId == 28682) then
+        if (school == Data.FIRE_SCHOOL and spellId == 28682) then
```
Comment (BreakBB) [inline Modules/Data/SpellCrit.lua:63]:
```suggestion
        if (ECS.IsWotlk and school == Data.FIRE_SCHOOL and spellId == 11129) then
            mod = mod + 50 -- 50% from Combustion
        end
        if (ECS.IsWotlk and school == Data.FIRE_SCHOOL and spellId == 28682) then
```

File: Modules/Data/SpellCrit.lua [hunk 7]
```diff
@@ -60,15 +60,9 @@ function _SpellCrit:GetSpellCritFromBuffs(school)
...
             mod = mod + (count * 10) -- 10% for each stack from Combustion
         end
```
Comment (BreakBB) [inline Modules/Data/SpellCrit.lua:65]:
```suggestion
        end
        if ((not ECS.IsWotlk) and school == Data.FIRE_SCHOOL and spellId == 11129) then
            mod = mod + 10 -- 10% from Combustion
        end
```

File: Modules/Data/SpellCrit.lua [hunk 8]
```diff
@@ -186,7 +180,7 @@ end
 
 function _SpellCrit:GetItemModifierHolyCrit()
     local mainHand, _ = GetInventoryItemID("player", 16)
-    if mainHand == 18608 then
+    if ECS.IsClassic and mainHand == 18608 then
```
Comment (BreakBB) [inline Modules/Data/SpellCrit.lua:183]:
```suggestion
    if mainHand == 18608 then
```

**Review by BreakBB — COMMENTED** [review]
Same as with the other change. Lets not do these changes in this PR as they are already part of #354

File: Modules/Data/SpellHit.lua [hunk 9]
```diff
@@ -123,7 +123,7 @@ function _SpellHit:GetSpellHitFromBuffs()
             otherDraeneiInGroup = true
         end
 
-        if spellId == 30708 then
+        if ECS.IsTbc and spellId == 30708 then
```
Comment (BreakBB) [inline Modules/Data/SpellHit.lua:126]:
```suggestion
        if spellId == 30708 then
```

This is also part of #354
